### ISSUE TITLE
History Id Section

### ISSUE THREAD

**Issue by isahua16** [Tsukumogami-Software/milou#11]
When using the example code for the history section:

```
# The company history
histories:
  - header: Built with milou
    text: This press kit is generated by milou
  - header: Free and Open Source
    text: Find it on GitHub https://github.com/Tsukumogami-Software/milou
```

The HTML generated doesn't include a header with an id of history, which means the history button in the nav doesn't work.
<img width="993" alt="Screenshot 2024-08-06 at 4 39 30 PM" src="https://github.com/user-attachments/assets/adddd7a3-9943-44da-8f10-bc6ddf8035e4">
