### ISSUE TITLE
No widget for Playstation? Xbox? Switch?

### ISSUE THREAD

**Issue by keitzer** [Tsukumogami-Software/milou#14]
Assuming due to lack of API / external widget by sony, but if such a widget exists it would be nice to have

eg, in the `data.yml` of a product:

```
# Store links (ID)
widgets:
  playstation: 10008652 # I dont think this exists yet?
  steam: 2472700
```

And similar examples for other consoles basically.

Feel free to close this issue if it's not possible (nor worth your time to create a custom widget)
